ALTER SESSION SET CONTAINER=&1;

CREATE USER &2 IDENTIFIED BY &3 DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;

GRANT CONNECT TO &2 ;
GRANT RESOURCE TO &2 ;

GRANT UNLIMITED TABLESPACE TO &2 ;
exit;